# Generated by Django 2.2 on 2020-09-24 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200923_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='chatproject',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='project',
            name='chat',
        ),
        migrations.AddField(
            model_name='chatproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sala',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ChatProject'),
        ),
        migrations.AlterField(
            model_name='chatproject',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
