# Generated by Django 2.2 on 2020-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200924_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkProposals',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Sin Cotizar', 'Sin cotizar'), ('Cotizado', 'Cotizado'), ('Cotización Aprobada', 'Cotización Aprobado'), ('Cotización Rechazada', 'Cotización Rechazada'), ('En Desarrollo', 'En Desarrollo'), ('En Revisión', 'En Revisión'), ('Terminado', 'Terminado')], max_length=20, null=True),
        ),
    ]
